### ISSUE TITLE
Cannot import Basscss modules 

### ISSUE THREAD

**Issue by hew** [basscss/postcss-basscss#1]
I tried your React-Basscss-hot-boilerplate on a couple different machines. Get this error when loading webpack:

![picture](http://f.cl.ly/items/0r3V0a281m273C3h2U3J/Image%202015-07-15%20at%203.21.44%20PM.png)

If I comment out basscss-base-reset, webpack fails on the next module listed. 

Sorry if this is the wrong place for this report. My suspicion is the error is specific to postcss-basscss, though (and the boilerplate has no issues).

**Comment by jxnblk** [comment]
Yeah I've been using npm 3, which didn't cause issues, but updated when I noticed that. Have you pulled the latest from the boilerplate repo. It's a patch version for this module

**Comment by hew** [comment]
I upgraded to NPM 3. All is working as intended. 

Maybe had something to do with the dependency tree? 

In any case, thanks. :)

**Comment by jxnblk** [comment]
Yeah npm keeps all deps at the same level if possible, the patch _should_ work for npm v2 though

**Comment by hew** [comment]
I cloned the version giving me the NPM 2 errors about an hour ago, so it would have been the latest version.
