### ISSUE TITLE
Include a webpack example of usage with latest postcss-cssnext loaders

### ISSUE THREAD

**Issue by BinahLinden** [basscss/postcss-basscss#3]
This plugin is currently not working for me with webpack and postcss loaders would be nice to see an example usage with the latest loaders. Here is a link to a fork of the example react-basscss-hot-boilerplate repo where I've removed cssnext and updated to postcss-cssnext in hopes to get it working. If anyone is reading and had a few minutes maybe could look at configuration and see if anything stands out as why it is not working.

[https://github.com/simplesthing/react-basscss-hot-boilerplate/blob/master/webpack.config.js](https://github.com/simplesthing/react-basscss-hot-boilerplate/blob/master/webpack.config.js)

Thanks

**Comment by BinahLinden** [comment]
I found the issue which is trying to use css modules with rebass and postcss, if i remove the cssmodules bit it is working as expected.

**Comment by jxnblk** [comment]
Hey, sorry. I started this module out as an experiment and really never took the time to revisit it...

If you don't need or want the [remove-mutations](https://github.com/jxnblk/postcss-remove-mutations) or remove-ids part, it's probably simplest to just use the Basscss modules as CSS, which _should_ work with CSS Modules.

**Comment by BinahLinden** [comment]
Ahh thanks for replying, I am new to MSS, ICSS or whatever it should be called, but I realize now that I need to be using composition with modules anyways, and that is another great reason why it shouldn't work with modules. I can use this plugin for other things that don't require so much complexity though, Thanks for making it!
